# Arguments example
#These are variables which can be overwritten during image build
#Argument can be defined anywhere
#Argment is only used at the time of image build . Not at the time of running container
ARG IMAGE_VERSION=latest
ARG OS_NAME=ubuntu
FROM ubuntu:${IMAGE_VERSION}
FROM ubuntu:${OS_NAME}
CMD [ "/bin/bash" ]

