#running container using command
FROM ubuntu:latest
#run command is generally used to start a web server by running a program
RUN apt-get -y install python3
#to build image use : docker build . -t image_name
CMD [ "/bin/bash" ]

#