#multiple cmd 
FROM ubuntu:latest

#Command overwritten
#Can only be written in -it (interactive) mode
CMD ["/bin/echo","Aloha 1"]
CMD ["/bin/echo","Aloha 2"]
CMD ["/bin/echo","Aloha 3"]
CMD ["/bin/echo","Aloha 4"]
#only the last CMD command will be executed
